// Định nghĩa các chuỗi ngôn ngữ
export const languages = {
  vi: {
    // Common
    appName: "Workly",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    add: "Thêm",
    confirm: "Xác nhận",
    yes: "Có",
    no: "Không",
    ok: "OK",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    retry: "Thử lại",
    warning: "Cảnh báo",
    viewAll: "Xem tất cả",
    showLogs: "Hiện nhật ký",
    hideLogs: "Ẩn nhật ký",

    // Home
    todayShifts: "Ca làm việc hôm nay",
    weeklySchedule: "Lịch tuần này",
    weather: "Thời tiết",
    notes: "Ghi chú công việc",
    noShiftsToday: "Không có ca làm việc nào hôm nay",
    addNewShift: "Thêm ca mới",
    noNotes: "Không có ghi chú nào",
    addNewNote: "Thêm ghi chú mới",
    notCheckedIn: "Chưa check-in",
    checkedInNotOut: "Đã check-in, chưa check-out",
    checkedInAndOut: "Đã check-in và check-out",
    goToWork: "Đi Làm",
    logCheckIn: "Chấm Công Vào",
    logPunch: "Ký Công",
    logCheckOut: "Chấm Công Ra",
    logComplete: "Hoàn Tất",
    workingFor: "Đang làm việc được {duration}",
    welcomeMessage:
      "Chào mừng đến với Workly, ứng dụng quản lý ca làm việc cá nhân của bạn!",
    weatherAlert: "Thời tiết hiện tại: {temperature}°C - {condition}",
    shiftInstructions:
      "Nhấn Đi Làm để bắt đầu ca làm việc, sau đó sử dụng Chấm Công Vào khi bạn đến nơi.",
    reminderNote:
      "Bạn có {count} lời nhắc đã lên lịch cho hôm nay. Xem tất cả.",
    helpText: "Cần trợ giúp? Truy cập trung tâm trợ giúp hoặc liên hệ hỗ trợ.",
    todayLogs: "Nhật ký hôm nay",
    activeShift: "Ca làm việc hiện tại",
    punch: "Ký công",

    // Settings
    settings: "Cài đặt",
    interface: "Giao diện",
    notifications: "Thông báo",
    data: "Dữ liệu",
    other: "Khác",
    multiButtonMode: "Chế độ nút đa năng",
    firstDayOfWeek: "Ngày bắt đầu tuần",
    timeFormat: "Định dạng giờ",
    theme: "Giao diện",
    alarmSound: "Âm thanh báo thức",
    alarmVibration: "Rung báo thức",
    shiftChangeReminder: "Nhắc đổi ca",
    weatherWarning: "Cảnh báo thời tiết",
    updateLocation: "Cập nhật vị trí",
    language: "Ngôn ngữ",
    about: "Về ứng dụng",
    hapticFeedback: "Phản hồi xúc giác",

    // Shifts
    shiftList: "Danh sách ca làm việc",
    shiftDetails: "Chi tiết ca làm việc",
    addShift: "Thêm ca làm việc",
    shiftName: "Tên ca làm việc",
    startTime: "Thời gian bắt đầu",
    endTime: "Thời gian kết thúc",
    maxEndTime: "Thời gian kết thúc tối đa",
    departureTime: "Thời gian xuất phát",
    officeEndTime: "Thời gian kết thúc giờ hành chính",
    breakMinutes: "Thời gian nghỉ (phút)",
    remindBeforeStart: "Nhắc trước khi vào ca (phút)",
    remindAfterEnd: "Nhắc sau khi kết thúc ca (phút)",
    penaltyRoundingMinutes: "Làm tròn phút phạt (phút)",
    requirePunch: "Yêu cầu ký công",
    daysApplied: "Ngày áp dụng",
    noShifts: "Chưa có ca làm việc nào",
    addShiftPrompt: "Nhấn nút bên dưới để thêm ca mới",
    deleteConfirm: "Bạn có chắc chắn muốn xóa ca",
    nameRequired: "Vui lòng nhập tên ca làm việc",
    daysRequired: "Vui lòng chọn ít nhất một ngày trong tuần",
    startBeforeEnd:
      "Thời gian bắt đầu phải trước thời gian kết thúc giờ hành chính",
    officeEndBeforeMax:
      "Thời gian kết thúc giờ hành chính phải trước hoặc bằng thời gian kết thúc tối đa",
    mon: "T2",
    tue: "T3",
    wed: "T4",
    thu: "T5",
    fri: "T6",
    sat: "T7",
    sun: "CN",
    shiftTip: "Đối với ca qua đêm, hãy đặt thời gian kết thúc sau nửa đêm.",
    breakExplanation:
      "Thời gian nghỉ {duration} phút sẽ được tự động trừ khỏi giờ làm việc của bạn.",

    // Alarm
    alarm: "Báo thức",
    timeToWork: "Đến giờ làm việc",
    shiftStartingSoon: "Ca {name} sẽ bắt đầu trong {minutes} phút nữa.",
    shiftEndingSoon: "Ca {name} sẽ kết thúc trong {minutes} phút nữa.",
    dismissAlarm: "Tắt báo thức",
    displayTime: "Thời gian hiển thị",

    // Backup
    backup: "Sao lưu",
    backupData: "Sao lưu dữ liệu",
    restoreData: "Khôi phục dữ liệu",
    exportSuccess: "Xuất dữ liệu thành công",
    importSuccess: "Nhập dữ liệu thành công",
    exportError: "Lỗi khi xuất dữ liệu",
    importError: "Lỗi khi nhập dữ liệu",
    confirmRestore: "Xác nhận khôi phục",
    confirmRestoreMessage:
      "Dữ liệu hiện tại sẽ bị ghi đè. Bạn có chắc chắn muốn tiếp tục?",
    importData: "Nhập dữ liệu",

    // Attendance
    checkInSuccess: "Chấm công vào thành công",
    checkOutSuccess: "Chấm công ra thành công",
    confirmCheckOut: "Xác nhận chấm công ra",
    confirmCheckOutMessage: "Bạn có chắc chắn muốn chấm công ra bây giờ?",
  },

  en: {
    // Common
    appName: "Workly",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    ok: "OK",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    retry: "Retry",
    warning: "Warning",
    viewAll: "View All",
    showLogs: "Show Logs",
    hideLogs: "Hide Logs",

    // Home
    todayShifts: "Today's Shifts",
    weeklySchedule: "Weekly Schedule",
    weather: "Weather",
    notes: "Work Notes",
    noShiftsToday: "No shifts today",
    addNewShift: "Add new shift",
    noNotes: "No notes",
    addNewNote: "Add new note",
    notCheckedIn: "Not checked in",
    checkedInNotOut: "Checked in, not checked out",
    checkedInAndOut: "Checked in and checked out",
    goToWork: "Go to Work",
    logCheckIn: "Check In",
    logPunch: "Punch",
    logCheckOut: "Check Out",
    logComplete: "Complete",
    workingFor: "Working for {duration}",
    welcomeMessage: "Welcome to Workly, your personal shift management app!",
    weatherAlert: "Current weather: {temperature}°C - {condition}",
    shiftInstructions:
      "Tap Go to Work to start your shift, then use Check In when you arrive.",
    reminderNote: "You have {count} reminder(s) scheduled for today. View all.",
    helpText: "Need help? Visit our help center or contact support.",
    todayLogs: "Today's Logs",
    activeShift: "Active Shift",
    punch: "Punch",

    // Settings
    settings: "Settings",
    interface: "Interface",
    notifications: "Notifications",
    data: "Data",
    other: "Other",
    multiButtonMode: "Multi-button Mode",
    firstDayOfWeek: "First Day of Week",
    timeFormat: "Time Format",
    theme: "Theme",
    alarmSound: "Alarm Sound",
    alarmVibration: "Alarm Vibration",
    shiftChangeReminder: "Shift Change Reminder",
    weatherWarning: "Weather Warning",
    updateLocation: "Update Location",
    language: "Language",
    about: "About",
    hapticFeedback: "Haptic Feedback",

    // Shifts
    shiftList: "Shift List",
    shiftDetails: "Shift Details",
    addShift: "Add Shift",
    shiftName: "Shift Name",
    startTime: "Start Time",
    endTime: "End Time",
    maxEndTime: "Maximum End Time",
    departureTime: "Departure Time",
    officeEndTime: "Office End Time",
    breakMinutes: "Break Minutes",
    remindBeforeStart: "Remind Before Start (minutes)",
    remindAfterEnd: "Remind After End (minutes)",
    penaltyRoundingMinutes: "Penalty Rounding Minutes",
    requirePunch: "Require Punch",
    daysApplied: "Days Applied",
    noShifts: "No shifts yet",
    addShiftPrompt: "Press the button below to add a new shift",
    deleteConfirm: "Are you sure you want to delete the shift",
    nameRequired: "Please enter a shift name",
    daysRequired: "Please select at least one day of the week",
    startBeforeEnd: "Start time must be before office end time",
    officeEndBeforeMax:
      "Office end time must be before or equal to maximum end time",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    shiftTip: "For overnight shifts, set the end time to be after midnight.",
    breakExplanation:
      "A {duration} minute break is automatically deducted from your work hours.",

    // Alarm
    alarm: "Alarm",
    timeToWork: "Time to work",
    shiftStartingSoon: "Shift {name} will start in {minutes} minutes.",
    shiftEndingSoon: "Shift {name} will end in {minutes} minutes.",
    dismissAlarm: "Dismiss Alarm",
    displayTime: "Display time",

    // Backup
    backup: "Backup",
    backupData: "Backup Data",
    restoreData: "Restore Data",
    exportSuccess: "Data exported successfully",
    importSuccess: "Data imported successfully",
    exportError: "Error exporting data",
    importError: "Error importing data",
    confirmRestore: "Confirm Restore",
    confirmRestoreMessage:
      "Current data will be overwritten. Are you sure you want to continue?",
    importData: "Import Data",

    // Attendance
    checkInSuccess: "Check-in successful",
    checkOutSuccess: "Check-out successful",
    confirmCheckOut: "Confirm Check Out",
    confirmCheckOutMessage: "Are you sure you want to check out now?",
  },
};
